name: release
on:
  push:
    branches:
      - main

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: check version diff
        id: check
        run: |
          if [ "`git diff HEAD HEAD^ package.json | grep version`" ]; then
            version=$(cat package.json | jq -r .version)
            echo "release version: $version"
            echo "version=$version" >> $GITHUB_OUTPUT
          fi
    outputs:
      version: ${{ steps.check.outputs.version }}

  npm-release:
    needs: check
    if: needs.check.outputs.version != ''
    name: npm-release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          registry-url: 'https://registry.npmjs.org'
      - run: bun install
      - name: publish npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}